import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

file1 = pd.read_csv('test.csv')
file1 = file1.rename(columns={'team': 'Team'})

file2 = pd.read_csv('Final_Team_Averages_2023_2024.csv')
file2 = file2.rename(columns={'team': 'Team'})

file3 = pd.read_csv('ppg.csv')
file3 = file3.rename(columns={'team': 'Team'})
file3['2023'] = pd.to_numeric(file3['2023'], errors='coerce')

# add PPG to file3 column names using a loop
for col in file3.columns:
    if col != 'Team':
        file3 = file3.rename(columns={col: f'PPG {col}'})



# Create a Dictionary with file1 and file2 team as names
team_names = {
'Alabama': 'Alabama Crimson Tide',
'Cal Poly': 'Cal Poly Mustangs',
'South Dakota': 'South Dakota Coyotes',
'Winthrop': 'Winthrop Eagles',
'New Mexico': 'New Mexico Lobos',
'UCF': 'UCF Knights',
'Alabama A&M': 'Alabama A&M Bulldogs',
'Bryant': 'Bryant Bulldogs',
'N Florida': 'North Florida Ospreys',
'SC Upstate': 'South Carolina Upstate Spartans',
'Akron': 'Akron Zips',
'CS Northridge': 'Cal State Northridge Matadors',
'W Kentucky': 'Western Kentucky Hilltoppers',
'Grand Canyon': 'Grand Canyon Lopes',
'Indiana St': 'Indiana State Sycamores',
'Illinois': 'Illinois Fighting Illini',
'Fresno St': 'Fresno State Bulldogs',
'Tennessee St': 'Tennessee State Tigers',
'Morgan St': 'Morgan State Bears',
'Kentucky': 'Kentucky Wildcats',
'Samford': 'Samford Bulldogs',
'AR-Pine Bluff': 'Arkansas-Pine Bluff Golden Lions',
'UMass': 'Massachusetts Minutemen',
'Mercer': 'Mercer Bears',
'Delaware St': 'Delaware State Hornets',
'Cornell': 'Cornell Big Red',
'Southern Miss': 'Southern Miss Golden Eagles',
'W Carolina': 'Western Carolina Catamounts',
'Buffalo': 'Buffalo Bulls',
'Ohio': 'Ohio Bobcats',
'St John\'s': 'St. John\'s Red Storm',
'Washington St': 'Washington State Cougars',
'Dartmouth': 'Dartmouth Big Green',
'San Diego': 'San Diego Toreros',
'Texas So': 'Texas Southern Tigers',
'Gonzaga': 'Gonzaga Bulldogs',
'S Carolina St': 'South Carolina State Bulldogs',
'Memphis': 'Memphis Tigers',
'Kennesaw St': 'Kennesaw State Owls',
'UMBC': 'UMBC Retrievers',
'Oklahoma St': 'Oklahoma State Cowboys',
'Georgia So': 'Georgia Southern Eagles',
'Quinnipiac': 'Quinnipiac Bobcats',
'Michigan': 'Michigan Wolverines',
'North Carolina': 'North Carolina Tar Heels',
'Rhode Island': 'Rhode Island Rams',
'Fordham': 'Fordham Rams',
'Temple': 'Temple Owls',
'Iowa': 'Iowa Hawkeyes',
'Florida Intl': 'Florida International Panthers',
'Prairie View': 'Prairie View A&M Panthers',
'Arizona': 'Arizona Wildcats',
'Jackson St': 'Jackson State Tigers',
'Lindenwood': 'Lindenwood Lions',
'Florida Atlantic': 'Florida Atlantic Owls',
'N Illinois': 'Northern Illinois Huskies',
'Arizona St': 'Arizona State Sun Devils',
'Columbia': 'Columbia Lions',
'Charleston': 'Charleston Cougars',
'UT Rio Grande': 'UT Rio Grande Valley Vaqueros',
'NC Asheville': 'UNC Asheville Bulldogs',
'Penn St': 'Penn State Nittany Lions',
'Arkansas St': 'Arkansas State Red Wolves',
'Florida St': 'Florida State Seminoles',
'S Florida': 'South Florida Bulls',
'Purdue FW': 'Purdue Fort Wayne Mastodons',
'Howard': 'Howard Bison',
'Iowa St': 'Iowa State Cyclones',
'Youngstown St': 'Youngstown State Penguins',
'Florida': 'Florida Gators',
'Arkansas': 'Arkansas Razorbacks',
'New Orleans': 'New Orleans Privateers',
'Maryland': 'Maryland Terrapins',
'Rutgers': 'Rutgers Scarlet Knights',
'LSU': 'LSU Tigers',
'Santa Clara': 'Santa Clara Broncos',
'Sacred Heart': 'Sacred Heart Pioneers',
'William & Mary': 'William & Mary Tribe',
'Vanderbilt': 'Vanderbilt Commodores',
'Miami OH': 'Miami (OH) RedHawks',
'Syracuse': 'Syracuse Orange',
'UAB': 'UAB Blazers',
'Bucknell': 'Bucknell Bison',
'UTSA': 'UTSA Roadrunners',
'Georgia Tech': 'Georgia Tech Yellow Jackets',
'Belmont': 'Belmont Bruins',
'Ohio St': 'Ohio State Buckeyes',
'Gardner-Webb': 'Gardner-Webb Runnin\' Bulldogs',
'Delaware': 'Delaware Blue Hens',
'UC Irvine': 'UC Irvine Anteaters',
'Charleston So': 'Charleston Southern Buccaneers',
'Abl Christian': 'Abilene Christian Wildcats',
'Mississippi St': 'Mississippi State Bulldogs',
'Southern': 'Southern Jaguars',
'S Utah': 'Southern Utah Thunderbirds',
'Queens': 'Queens University Royals',
'Portland': 'Portland Pilots',
'La Salle': 'La Salle Explorers',
'Mississippi': 'Ole Miss Rebels',
'Middle Tenn': 'Middle Tennessee Blue Raiders',
'Illinois Chicago': 'UIC Flames',
'NC Central': 'North Carolina Central Eagles',
'Bowling Green': 'Bowling Green Falcons',
'North Dakota': 'North Dakota Fighting Hawks',
'Longwood': 'Longwood Lancers',
'SMU': 'SMU Mustangs',
'Georgia St': 'Georgia State Panthers',
'California': 'California Golden Bears',
'Robert Morris': 'Robert Morris Colonials',
'Le Moyne': 'Le Moyne Dolphins',
'Nebraska': 'Nebraska Cornhuskers',
'Xavier': 'Xavier Musketeers',
'Alabama St': 'Alabama State Hornets',
'S Dakota St': 'South Dakota State Jackrabbits',
'Missouri': 'Missouri Tigers',
'Marshall': 'Marshall Thundering Herd',
'Milwaukee': 'Milwaukee Panthers',
'Auburn': 'Auburn Tigers',
'Iona': 'Iona Gaels',
'F Dickinson': 'Fairleigh Dickinson Knights',
'Wichita St': 'Wichita State Shockers',
'C Arkansas': 'Central Arkansas Bears',
'Utah Valley': 'Utah Valley Wolverines',
'Oklahoma': 'Oklahoma Sooners',
'Bethune': 'Bethune-Cookman Wildcats',
'Chicago St': 'Chicago State Cougars',
'Utah': 'Utah Utes',
'Stetson': 'Stetson Hatters',
'St Thomas': 'St. Thomas-Minnesota Tommies',
'UC Riverside': 'UC Riverside Highlanders',
'Indiana': 'Indiana Hoosiers',
'Kansas': 'Kansas Jayhawks',
'UMass Lowell': 'UMass Lowell River Hawks',
'N Colorado': 'Northern Colorado Bears',
'BYU': 'BYU Cougars',
'Michigan St': 'Michigan State Spartans',
'Oregon': 'Oregon Ducks',
'Yale': 'Yale Bulldogs',
'Pepperdine': 'Pepperdine Waves',
'UTEP': 'UTEP Miners',
'San Francisco': 'San Francisco Dons',
'W Michigan': 'Western Michigan Broncos',
'UT Arlington': 'UT Arlington Mavericks',
'Toledo': 'Toledo Rockets',
'Tenn Tech': 'Tennessee Tech Golden Eagles',
'Louisville': 'Louisville Cardinals',
'Sam Houston': 'Sam Houston Bearkats',
'NC A&T': 'North Carolina A&T Aggies',
'Nicholls': 'Nicholls Colonels',
'Wisconsin': 'Wisconsin Badgers',
'Denver': 'Denver Pioneers',
'Army': 'Army Black Knights',
'Omaha': 'Omaha Mavericks',
'C Michigan': 'Central Michigan Chippewas',
'E Kentucky': 'Eastern Kentucky Colonels',
'Colorado': 'Colorado Buffaloes',
'Green Bay': 'Green Bay Phoenix',
'Coppin St': 'Coppin State Eagles',
'Albany': 'UAlbany Great Danes',
'USC': 'USC Trojans',
'S Indiana': 'Southern Indiana Screaming Eagles',
'Tulsa': 'Tulsa Golden Hurricane',
'SE Missouri St': 'Southeast Missouri State Redhawks',
'Detroit Mercy': 'Detroit Mercy Titans',
'Texas': 'Texas Longhorns',
'Portland St': 'Portland State Vikings',
'Utah Tech': 'Utah Tech Trailblazers',
'Georgia': 'Georgia Bulldogs',
'W Georgia': 'West Georgia Wolves',
'New Hampshire': 'New Hampshire Wildcats',
'Mt St Mary\'s': 'Mount St. Mary\'s Mountaineers',
'Manhattan': 'Manhattan Jaspers',
'Valparaiso': 'Valparaiso Beacons',
'CS Fullerton': 'Cal State Fullerton Titans',
'Saint Joseph\'s': 'Saint Joseph\'s Hawks',
'Wright St': 'Wright State Raiders',
'Jacksonville': 'Jacksonville Dolphins',
'Washington': 'Washington Huskies',
'Boston College': 'Boston College Eagles',
'Texas St': 'Texas State Bobcats',
'Loyola Chi': 'Loyola Chicago Ramblers',
'UT Martin': 'UT Martin Skyhawks',
'Brown': 'Brown Bears',
'S Illinois': 'Southern Illinois Salukis',
'E Michigan': 'Eastern Michigan Eagles',
'SF Austin': 'Stephen F. Austin Lumberjacks',
'Florida A&M': 'Florida A&M Rattlers',
'Oral Roberts': 'Oral Roberts Golden Eagles',
'E Carolina': 'East Carolina Pirates',
'Ball St': 'Ball State Cardinals',
'DePaul': 'DePaul Blue Demons',
'Marquette': 'Marquette Golden Eagles',
'Little Rock': 'Little Rock Trojans',
'Siena': 'Siena Saints',
'UC Davis': 'UC Davis Aggies',
'UL Monroe': 'UL Monroe Warhawks',
'G Washington': 'George Washington Revolutionaries',
'Pacific': 'Pacific Tigers',
'Cal Baptist': 'California Baptist Lancers',
'Kansas St': 'Kansas State Wildcats',
'E Texas A&M': 'East Texas A&M Lions',
'Saint Louis': 'Saint Louis Billikens',
'Tulane': 'Tulane Green Wave',
'VMI': 'VMI Keydets',
'Penn': 'Pennsylvania Quakers',
'Texas A&M': 'Texas A&M Aggies',
'Georgetown': 'Georgetown Hoyas',
'Loyola Mymt': 'Loyola Marymount Lions',
'Monmouth': 'Monmouth Hawks',
'SIU Edward': 'SIU Edwardsville Cougars',
'Norfolk St': 'Norfolk State Spartans',
'Chattanooga': 'Chattanooga Mocs',
'Princeton': 'Princeton Tigers',
'Miami': 'Miami Hurricanes',
'Austin Peay': 'Austin Peay Governors',
'Wake Forest': 'Wake Forest Demon Deacons',
'CS Bakersfield': 'Cal State Bakersfield Roadrunners',
'Kent St': 'Kent State Golden Flashes',
'Creighton': 'Creighton Bluejays',
'Montana': 'Montana Grizzlies',
'E Illinois': 'Eastern Illinois Panthers',
'Utah St': 'Utah State Aggies',
'San Jose St': 'San José State Spartans',
'N Kentucky': 'Northern Kentucky Norse',
'St Francis PA': 'St. Francis (PA) Red Flash',
'E Washington': 'Eastern Washington Eagles',
'N Alabama': 'North Alabama Lions',
'Texas Tech': 'Texas Tech Red Raiders',
'Pittsburgh': 'Pittsburgh Panthers',
'SE Louisiana': 'SE Louisiana Lions',
'Northeastern': 'Northeastern Huskies',
'Texas A&M-CC': 'Texas A&M-Corpus Christi Islanders',
'High Point': 'High Point Panthers',
'Butler': 'Butler Bulldogs',
'South Carolina': 'South Carolina Gamecocks',
'Maryland ES': 'Maryland Eastern Shore Hawks',
'UCSD': 'UC San Diego Tritons',
'Northwestern': 'Northwestern Wildcats',
'Notre Dame': 'Notre Dame Fighting Irish',
'Tarleton St': 'Tarleton State Texans',
'TCU': 'TCU Horned Frogs',
'Seattle': 'Seattle U Redhawks',
'Harvard': 'Harvard Crimson',
'Bellarmine': 'Bellarmine Knights',
'Providence': 'Providence Friars',
'Binghamton': 'Binghamton Bearcats',
'N Dakota St': 'North Dakota State Bison',
'Furman': 'Furman Paladins',
'NJIT': 'NJIT Highlanders',
'Lehigh': 'Lehigh Mountain Hawks',
'Hawai\'i': 'Hawai\'i Rainbow Warriors',
'San Diego St': 'San Diego State Aztecs',
'Lipscomb': 'Lipscomb Bisons',
'Stanford': 'Stanford Cardinal',
'N Arizona': 'Northern Arizona Lumberjacks',
'Old Dominion': 'Old Dominion Monarchs',
'Troy': 'Troy Trojans',
'Idaho': 'Idaho Vandals',
'NC Wilmington': 'UNC Wilmington Seahawks',
'Baylor': 'Baylor Bears',
'Colorado St': 'Colorado State Rams',
'Long Beach St': 'Long Beach State Beach',
'Louisiana': 'Louisiana Ragin\' Cajuns',
'Navy': 'Navy Midshipmen',
'VCU': 'VCU Rams',
'Rice': 'Rice Owls',
'Murray St': 'Murray State Racers',
'Evansville': 'Evansville Purple Aces',
'Colgate': 'Colgate Raiders',
'Idaho St': 'Idaho State Bengals',
'Bradley': 'Bradley Braves',
'Liberty': 'Liberty Flames',
'Dayton': 'Dayton Flyers',
'Cleveland St': 'Cleveland State Vikings',
'Montana St': 'Montana State Bobcats',
'Lamar': 'Lamar Cardinals',
'Loyola MD': 'Loyola Maryland Greyhounds',
'Duke': 'Duke Blue Devils',
'Charlotte': 'Charlotte 49ers',
'UCSB': 'UC Santa Barbara Gauchos',
'Louisiana Tech': 'Louisiana Tech Bulldogs',
'George Mason': 'George Mason Patriots',
'Fairfield': 'Fairfield Stags',
'Virginia Tech': 'Virginia Tech Hokies',
'Maine': 'Maine Black Bears',
'Alcorn St': 'Alcorn State Braves',
'Missouri St': 'Missouri State Bears',
'LIU': 'Long Island University Sharks',
'Lafayette': 'Lafayette Leopards',
'Purdue': 'Purdue Boilermakers',
'Jacksonville St': 'Jacksonville State Gamecocks',
'Hampton': 'Hampton Pirates',
'Presbyterian': 'Presbyterian Blue Hose',
'Clemson': 'Clemson Tigers',
'UConn': 'UConn Huskies',
'West Virginia': 'West Virginia Mountaineers',
'The Citadel': 'The Citadel Bulldogs',
'UCLA': 'UCLA Bruins',
'Miss Valley St': 'Mississippi Valley State Delta Devils',
'C Connecticut': 'Central Connecticut Blue Devils',
'Tennessee': 'Tennessee Volunteers',
'Grambling': 'Grambling Tigers',
'Weber St': 'Weber State Wildcats',
'Oakland': 'Oakland Golden Grizzlies',
'Campbell': 'Campbell Fighting Camels',
'Boise St': 'Boise State Broncos',
'Holy Cross': 'Holy Cross Crusaders',
'UNLV': 'UNLV Rebels',
'IU Indy': 'IU Indianapolis Jaguars',
'Davidson': 'Davidson Wildcats',
'J Madison': 'James Madison Dukes',
'New Mexico St': 'New Mexico State Aggies',
'Canisius': 'Canisius Golden Griffins',
'Duquesne': 'Duquesne Dukes',
'McNeese': 'McNeese Cowboys',
'Illinois St': 'Illinois State Redbirds',
'Cincinnati': 'Cincinnati Bearcats',
'NC State': 'NC State Wolfpack',
'FGCU': 'FGCU Eagles',
'Elon': 'Elon Phoenix',
'W Illinois': 'Western Illinois Leathernecks',
'Kansas City': 'Kansas City Roos',
'Wyoming': 'Wyoming Cowboys',
'E Tennessee St': 'East Tennessee State Buccaneers',
'Minnesota': 'Minnesota Golden Gophers',
'Seton Hall': 'Seton Hall Pirates',
'S Alabama': 'South Alabama Jaguars',
'Hofstra': 'Hofstra Pride',
'Richmond': 'Richmond Spiders',
'Sacramento St': 'Sacramento State Hornets',
'Stonehill': 'Stonehill Skyhawks',
'Rider': 'Rider Broncs',
'Niagara': 'Niagara Purple Eagles',
'Saint Peter\'s': 'Saint Peter\'s Peacocks',
'Incarnate Word': 'Incarnate Word Cardinals',
'Oregon St': 'Oregon State Beavers',
'Morehead St': 'Morehead State Eagles',
'Nevada': 'Nevada Wolf Pack',
'Drexel': 'Drexel Dragons',
'NC Greensboro': 'UNC Greensboro Spartans',
'Wofford': 'Wofford Terriers',
'N Iowa': 'Northern Iowa Panthers',
'NW State': 'Northwestern State Demons',
'St Bonaventure': 'St. Bonaventure Bonnies',
'Marist': 'Marist Red Foxes',
'Air Force': 'Air Force Falcons',
'Mercyhurst': 'Mercyhurst Lakers',
'Towson': 'Towson Tigers',
'Merrimack': 'Merrimack Warriors',
'Hou Christian': 'Houston Christian Huskies',
'Stony Brook': 'Stony Brook Seawolves',
'Boston U': 'Boston University Terriers',
'Radford': 'Radford Highlanders',
'Coastal Car': 'Coastal Carolina Chanticleers',
'App State': 'App State Mountaineers',
'American': 'American University Eagles',
'Saint Mary\'s': 'Saint Mary\'s Gaels',
'Houston': 'Houston Cougars',
'Villanova': 'Villanova Wildcats',
'Vermont': 'Vermont Catamounts',
'Virginia': 'Virginia Cavaliers',
'Wagner': 'Wagner Seahawks',
'N Texas': 'North Texas Mean Green',
'Drake': 'Drake Bulldogs',
'FGCU': 'Florida Gulf Coast Eagles',
}

reverse_team_names = {v: k for k, v in team_names.items()}

# Replace file2 team names with file1 team names using the dictionary (Remove any rows that do not match)
file2['Team'] = file2['Team'].map(reverse_team_names)
file2 = file2.dropna(subset=['Team'])
# alphabetize file2 by team
file2 = file2.sort_values(by=['Team'])

print(file2)
file2.to_csv('Final_Team_Averages_2023_2024_Updated.csv', index=False)

# Merge the two files on the team column
merged_file = pd.merge(file1, file2, on='Team')
merged_file['2023'] = pd.to_numeric(merged_file['2023'], errors='coerce')

merged_file = pd.merge(merged_file, file3, on='Team')
print(merged_file)

# Plot 2023 vs Avg Poss Per Game with regression line
plt.figure(figsize=(10, 6))
plt.scatter(merged_file['Avg Poss Per Game'], merged_file['2023'], alpha=0.7)
plt.title('2023 vs Avg Poss Per Game')
plt.xlabel('Avg Poss Per Game')
plt.ylabel('2023')

# Fit and plot regression line and r2 value
z = np.polyfit(merged_file['Avg Poss Per Game'], merged_file['2023'], 1)
p = np.poly1d(z)
plt.plot(merged_file['Avg Poss Per Game'], p(merged_file['Avg Poss Per Game']), color='red')
correlation_matrix = np.corrcoef(merged_file['Avg Poss Per Game'], merged_file['2023'])
correlation_xy = correlation_matrix[0,1]
r_squared = correlation_xy**2
print(f"R-squared: {r_squared}")
plt.grid()
plt.show()

# Plot 2023 vs Avg Points Per Game with regression line
plt.figure(figsize=(10, 6))
plt.scatter(merged_file['Avg Points Per Game'], merged_file['PPG 2023'], alpha=0.7)
plt.title('2023 vs Avg Points Per Game')
plt.xlabel('Avg Points Per Game')
plt.ylabel('PPG 2023')
# Fit and plot regression line and r2 value
z = np.polyfit(merged_file['Avg Points Per Game'], merged_file['PPG 2023'], 1)
p = np.poly1d(z)
plt.plot(merged_file['Avg Points Per Game'], p(merged_file['Avg Points Per Game']), color='red')
correlation_matrix = np.corrcoef(merged_file['Avg Points Per Game'], merged_file['PPG 2023'])
correlation_xy = correlation_matrix[0,1]
r_squared = correlation_xy**2
print(f"R-squared: {r_squared}")
plt.grid()
plt.show()
