[theme]
base="light"
primaryColor="#DAA520"
backgroundColor="#545353ff"
secondaryBackgroundColor="#FFFFFF"
textColor="#FFFFFF"
font="sans-serif"

[server]
headless = true

[client]
showErrorDetails = true


