[theme]
base="light"
primaryColor="#FFD700"
backgroundColor="#514f4fff"
secondaryBackgroundColor="#FFFFFF"
textColor="#FFFFFF"
font="sans-serif"

[server]
headless = true

[client]
showErrorDetails = true


